###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
    redis:
        image: 'redis:alpine'
        container_name: task-trek-redis
        ports:
            - '8081:6379'

    mysql:
        image: 'mysql:8.0'
        container_name: task-trek-mysql
        working_dir: /src
        volumes:
            - "./data:/var/lib/mysql/"
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - '8082:3306'

    webserver:
        image: 'nginx:alpine'
        container_name: task-trek-nginx
        working_dir: /src
        volumes:
            - './code:/code'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8080:80'

    php-fpm:
        build: phpdocker/php-fpm
        container_name: task-trek-php
        working_dir: /src
        volumes:
            - './code:/code'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini'
