name: Deploy to Production

on:
  push:
    branches:
      - deploy_automation  # Triggers when code is pushed/merged to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.HOSTGATOR_SSH_KEY }}

#      - name: Add Hostgator to known_hosts
#        run: |
#          mkdir -p ~/.ssh
#          ssh-keyscan -p 2222 ${{ secrets.HOSTGATOR_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Hostgator
        run: |
          git remote add production ssh://${{ secrets.HOSTGATOR_USER }}@${{ secrets.HOSTGATOR_HOST }}:2222/~/tasktrek.ca.github
          git push production deploy_automation
